/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    EduResourceCard: typeof import('./src/components/EduResourceCard.vue')['default']
    EduResourceEditor: typeof import('./src/components/EduResourceEditor.vue')['default']
    EduResourceList: typeof import('./src/components/EduResourceList.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    NavLeftPrimary: typeof import('./src/components/NavLeftPrimary.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    PatientsTable: typeof import('./src/components/PatientsTable.vue')['default']
    RequestTable: typeof import('./src/components/RequestTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/components/TextButton.vue')['default']
  }
}
