/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    NavLeftPrimary: typeof import('./src/components/NavLeftPrimary.vue')['default']
    NavLeftPrimaryDoctors: typeof import('./src/components/NavLeftPrimaryDoctors.vue')['default']
    NavLeftSecondary: typeof import('./src/components/NavLeftSecondary.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NIcon: typeof import('naive-ui')['NIcon']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
